name: Enforce Staging Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-staging:
    if: ${{ github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from staging
        if: ${{ github.event.pull_request.base.ref != 'staging' }}
        run: exit 1
